### ISSUE TITLE
delete_workloads alwas times out

### ISSUE THREAD

**Issue by FelixMoelders** [eclipse-ankaios/ank-sdk-python#40]
When trying to delete a workload via ankaios.delete_workload(workload_name, timeout=60.0) the action always times out.
I have set the timeout time manually to 60 seconds, this did not resolve the issue.

[2024-11-17 18:34:38] Timeout while waiting for the response.
[2024-11-17 18:34:38,990] ERROR in app: Exception on /deleteWorkloads [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ankaios-dashboard/DashboardAPI.py", line 92, in delete_workloads
    print(ank_comm_service.deleteWorkloads(request.json))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ankaios-dashboard/AnkCommunicationService.py", line 73, in deleteWorkloads
    ret = self.ankaios.delete_workload(workload_name, timeout=60.0)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ankaios_sdk/ankaios.py", line 628, in delete_workload
    raise e
  File "/usr/lib/python3.11/site-packages/ankaios_sdk/ankaios.py", line 625, in delete_workload
    response = self._send_request(request, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ankaios_sdk/ankaios.py", line 435, in _send_request
    raise e
  File "/usr/lib/python3.11/site-packages/ankaios_sdk/ankaios.py", line 433, in _send_request
    response = self._get_response_by_id(request.get_id(), timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ankaios_sdk/ankaios.py", line 411, in _get_response_by_id
    return self._responses[request_id].wait_for_response(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ankaios_sdk/_components/response.py", line 239, in wait_for_response
    raise TimeoutError("Timeout while waiting for the response.")
TimeoutError: Timeout while waiting for the response.

**Comment by krucod3** [comment]
Hi Felix, thanks for the bug report. Can you please also attach logs from the server and the agent(s)? 
It would also be very helpful if you also take a look and send us the string for the `workload_name` that you send in the `delete_workload` method. Please note that the expectation there is that an Ankaios workload name is sent and not the workload instance name, i.e., `test_workload` and not `test_workload.sdcdscdscsdc2q3dertcqwec3re.agent_A`.

**Comment by krucod3** [comment]
Unfortunately I cannot reproduce the problem at the moment.

**Comment by GabyUnalaq** [comment]
Can you run again but with the `DEBUG` logger?

`with Ankaios(AnkaiosLogLevel.DEBUG) as ankaios:`

**Comment by FelixMoelders** [comment]
Hi Kaloyan, yes i used the workload_name and not the workload itself. I will run it in Debug mode and try to retrieve more info.

**Comment by GabyUnalaq** [comment]
I could not reproduce the error. I attached the code that I run.

![image](https://github.com/user-attachments/assets/1c3a4ba4-9aeb-4f03-86e2-fb9134a87065)

**Comment by FelixMoelders** [comment]
The update from ank v0.5.0rc1 to v0.5.0 and reloading of the ankaios-sdk fixed the issue.
